apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
spec:
#  replicas: 2
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    # Pod definition starts here
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: jimmyshah83/pal-tracker:v3
          resources:
            limits:
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 150
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: welcome.message
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: management.endpoints.web.exposure.include
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
              value: "1"
          #kubectl create secret generic db-credentials --from-literal=SPRING_DATASOURCE_URL='jdbc:postgresql://ruby.db.elephantsql.com:5432/yeybcuij?user=yeybcuij&password=xxxx'
          envFrom:
            - secretRef:
                name: db-credentials
